Lineage pull request for: skeleton
cisagov/ansible-role-freeipa-client pull request #57
Opened 2023-04-27 13:27 UTC by cisagovbot

# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-ansible-role.git`](https://github.com/cisagov/skeleton-ansible-role.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

Remove any of the following that do not apply. These boxes should
remain unchecked until the pull request has been approved.

- [ ] Bump major, minor, patch, or pre-release version [as
      appropriate](https://semver.org/#semantic-versioning-specification-semver)
      via the `bump_version.sh` script *if* this repository is
      versioned *and* the changes in this PR [warrant a version
      bump](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api).

## ✅ Post-merge checklist ##

Remove any of the following that do not apply.

- [ ] Create a release.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2023-05-01 16:32 UTC, jsf9k requested changes
I'm requesting some minor wording changes.

2023-05-01 16:32 UTC, jsf9k commented on meta/main.yml
> +    # Amazon Linux 2023 does not not currently offer ipa
```suggestion
    # Amazon Linux 2023 does not not currently offer an IPA client package:
```

2023-05-01 16:32 UTC, jsf9k commented on molecule/default/molecule-no-systemd.yml
> +  # Amazon Linux 2023 does not currently offer ipa
```suggestion
  # Amazon Linux 2023 does not currently offer an IPA client package:
```

2023-05-01 16:32 UTC, jsf9k commented on molecule/default/molecule-with-systemd.yml
> +  # Amazon Linux 2023 does not currently offer ipa
```suggestion
  # Amazon Linux 2023 does not currently offer an IPA client package:
```

2023-05-03 14:23 UTC, jsf9k approved these changes

2023-05-03 14:25 UTC, dav3r approved these changes

2023-05-10 20:02 UTC, merged